export const CHANGEMARKD = '/Nav/CHANGE_MARKD';
export const CHANGEHEIGHT = '/Nav/CHANGE_HEIGHT' // 获得高度
export const CHANGEISDOWNPDF = '/Nav/CHANGE_ISDOWNPDF'

export const CHANGEBUTTONCLEARN = '/Nav/CHANGE_BUTTON_CLEARN' 