export const CHANGEMARKDOWNDATA = '/RightWrith/CHANGE_MARKDOWN_DATA';
export const CHANGESCROLLHEIGHTANDTOP = '/RightWrith/CHANGE_SCROLLHEIGHT_TOP';
export const CHANGEGETTEXTARRAYS = '/RightWrith/CHANGE_GETTEXT_ARRAYS';
